language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -U pytest
  - pip install -U codecov
script:
  - pytest
  - coverage run test_parse.py
after_success:
  - codecov